### ISSUE TITLE
Gravizo not rendering

### ISSUE THREAD

**Issue by njdro** [obedm503/bootmark#12]
When using http://gravizo.com/ to render graphiz dot syntax, bootmark does not render the images at all.  

Other products that perform similarly:
 - [Flatdoc](https://github.com/rstacruz/flatdoc) similarly does not render the markdown tag, but still renders the `<img` tag version.
 - Original [Strapdown](https://github.com/arturadib/strapdown) same as above.
 - Both [Strapdown+Navigation](https://github.com/marshyski/strapdown) and [Strapdown-Zeta](https://github.com/chaitin/strapdown-zeta) renders both properly, so it seems fixable

I'm using `python3 -m http.server` or `python2 -m SimpleHTTPServer` to serv.

Thank you

**Comment by obedm503** [comment]
can you show an example of your issue? 

It is for sure not an issue with the markdown parser. See the demo of just the parser with the some graphic [here](http://showdownjs.github.io/demo/#/!%5Bimg%5D(http%3A%2F%2Fg.gravizo.com%2Fg%3F%2520digraph%2520G%2520%7B%2520aize%2520%3D%25224%2C4%2522%3B%2520main%2520%5Bshape%3Dbox%5D%3B%2520main%2520-%253E%2520parse%2520%5Bweight%3D8%5D%3B%2520parse%2520-%253E%2520execute%3B%2520main%2520-%253E%2520init%2520%5Bstyle%3Ddotted%5D%3B%2520main%2520-%253E%2520cleanup%3B%2520execute%2520-%253E%2520%7B%2520make_string%3B%2520printf%7D%2520init%2520-%253E%2520make_string%3B%2520edge%2520%5Bcolor%3Dred%5D%3B%2520main%2520-%253E%2520printf%2520%5Bstyle%3Dbold%2Clabel%3D%2522100%2520times%2522%5D%3B%2520make_string%2520%5Blabel%3D%2522make%2520a%2520string%2522%5D%3B%2520node%2520%5Bshape%3Dbox%2Cstyle%3Dfilled%2Ccolor%3D%2522.7%2520.3%25201.0%2522%5D%3B%2520execute%2520-%253E%2520compare%3B%2520%7D))

if you want to try a live demo of bootmark go [here](https://obedm503.github.io/katex-latex/) and on the "live demo" section replace the existing text with `![graphic](`*graphic url*`)`

**Comment by njdro** [comment]
Link to screencap: [Selection_625.png](https://postimg.org/image/vnv6kri23/)
Link to HTML: (http://pastebin.com/raw/3H1cAgeN)
Link to markdown file (Readme.md): (http://pastebin.com/raw/yz8yrFHh)

If i copy the above raw text Readme.md into your live-demo, the `<img` tag renders, but not the markdown tag: [Selection_626.png](https://postimg.org/image/6j467ciln/)

The graph-text were copy pasted directly from gravizo to minimize error.

I just copy/pasted directly into showdown editor with same fail: [Selection_627.png](https://postimg.org/image/hwqpijt4b/)

**Comment by obedm503** [comment]
I think I found it. It seems that showdown doesn't like urls with spaces of line breaks in them. To solve it you have to use url encoded strings. Try pasting the url into your browser's searchbox:
```html
http://g.gravizo.com/g?
  digraph G {
    aize ="4,4";
    main [shape=box];
    main -> parse [weight=8];
    parse -> execute;
    main -> init [style=dotted];
    main -> cleanup;
    execute -> { make_string; printf}
    init -> make_string;
    edge [color=red];
    main -> printf [style=bold,label="100 times"];
    make_string [label="make a string"];
    node [shape=box,style=filled,color=".7 .3 1.0"];
    execute -> compare;
  }
```
it should automatically convert the spaces into `%20`s
```
http://g.gravizo.com/g?%20digraph%20G%20{%20aize%20=%224,4%22;%20main%20[shape=box];%20main%20-%3E%20parse%20[weight=8];%20parse%20-%3E%20execute;%20main%20-%3E%20init%20[style=dotted];%20main%20-%3E%20cleanup;%20execute%20-%3E%20{%20make_string;%20printf}%20init%20-%3E%20make_string;%20edge%20[color=red];%20main%20-%3E%20printf%20[style=bold,label=%22100%20times%22];%20make_string%20[label=%22make%20a%20string%22];%20node%20[shape=box,style=filled,color=%22.7%20.3%201.0%22];%20execute%20-%3E%20compare;%20}
```

it might be related to showdownjs/showdown#329, and as @tivie says, spaces are not valid

**Comment by njdro** [comment]
That's definaitly getting me in the right direction, it fixes the `<img` tag for certain, but trying the same with the markdown tag isn't resulting so nice.  thanks for the help!

edit: making a simpler graph for the markdown tag worked, so it seem maybe complex ones corrupt rendering somehow.  thanks again.
