### ISSUE TITLE
Limit TOC to given level

### ISSUE THREAD

**Issue by urmilparikh** [obedm503/bootmark#13]
Please add an option to limit TOC to a given level, e.g. up to level 2.

**Comment by obedm503** [comment]
this is addressed by ab92dd84e12d73cacc3be1998f843e2b5ed8da7e. it will soon be tested and merged to development

**Comment by obedm503** [comment]
this is now in development branch

use `config.html.tocLimit` and a number corresponding to the level of heading to limit to. `1` will only use `<h1>` but `3` will use from `<h1>` to `<h3>`. up to `6`
