### ISSUE TITLE
Inline HTML

### ISSUE THREAD

**Issue by jamiejackson** [obedm503/bootmark#16]
I use strapdown all the time, but I'm evaluating bootmark today. The first incompatibility I'm noticing is that bootmark seems to strip out any inline HTML:

```html
<!DOCTYPE html>
<html>
<head>
  <title>any tag - document</title>
  <script src="https://obedm503.github.io/bootmark/dist/bootmark.bundle.min.js"></script>
</head>
<body>

<div
	class="bootmark"
	data-html="{
		theme:'journal',
		indent: true
	}"
>


<table style="borders:1">
<tr><td>cell1</td><td>cell2</td></tr>
<tr><td>cell3</td><td>cell4</td></tr>
</table>

	
# Markdown text goes in here

## Chapter 1

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris aliquam dictum imperdiet. Cras at sem scelerisque, tristique ex vel, suscipit ligula. Duis at est sed massa ultrices accumsan ut ut massa. Cras enim nibh, dictum id scelerisque vel, laoreet eu ipsum. Nam ut turpis nibh. Mauris vel urna in dolor ultrices suscipit. Pellentesque viverra et tellus sit amet viverra. Suspendisse convallis urna quis enim vehicula tincidunt. In orci diam, dapibus vel odio sit amet, malesuada porta felis. Aliquam egestas risus sit amet efficitur tempus. Pellentesque sollicitudin sollicitudin est in sodales.

Nulla sed arcu non diam accumsan imperdiet. Praesent vulputate tincidunt augue, a mattis augue fermentum vehicula. Suspendisse congue ligula mauris, at mollis quam convallis et. Sed congue tempor convallis. Maecenas libero lacus, dictum sed gravida in, aliquet eget mauris. Proin consequat et felis eget dictum. Proin lobortis aliquet leo id ornare. Nam eget porttitor lorem. Nulla sit amet commodo tellus, nec aliquet nunc. Vivamus porta commodo tellus, quis imperdiet neque consectetur id. Vestibulum pretium quis diam eget aliquet. Cras sem mauris, feugiat at sem vitae, ornare feugiat turpis. Pellentesque condimentum enim a risus vehicula, et fermentum libero luctus. Nulla egestas est ut felis molestie, vitae interdum ante semper. Nam in tortor ac dui maximus vehicula vel ac nibh. Sed eleifend diam eu sapien elementum, eu cursus mi pretium.

</div>
</body>
</html>
```
Strapdown would have rendered the table, whereas bootmark seems to strip out HTML and run the cell contents together.

How does one do this in bootmark?

**Comment by obedm503** [comment]
this seems to be related to #14. can you test this with the code in the development branch and see if it persists?

**Comment by jamiejackson** [comment]
#14 is the opposite use case. That ticket wants "tags" that are in code blocks to output escaped and un-rendered. In other words:
```
`<stong>hello</strong>`
```
Should render as

`<strong>hello</strong>`

----

#16 ticket wants HTML tags _to render_ (when not in markdown code blocks).
```
<strong>hello</strong>
```
Should render as:

**hello**

----

FYI, the development branch doesn't fix #16.

**Comment by obedm503** [comment]
I know that #14 fixed something else but it might have fixed this also

this fiddle uses rawgit to test if this is not a problem under the current code in the development branch, and it works:
https://jsfiddle.net/hpo787fe/

**Comment by jamiejackson** [comment]
Sorry, you're right. It fooled me the way that the repo's examples point to a remote JS source. I was thinking that if I cloned the repo, the examples would be relatively linked and would use the latest (from the clone).

I understand why the examples are the way they are (to show _users_ how to use bootmark), but it's confusing from the perspective of a (would be) bootmark developer.

**Comment by obedm503** [comment]
> I understand why the examples are the way they are (to show users how to use bootmark), but it's confusing from the perspective of a (would be) bootmark developer.

yes the examples are meant to work as starters/templates that people can use to get up and running easily. I'll add a note in `EXAMPLES.md` about that for clarification.
