### ISSUE TITLE
Rendering Issues

### ISSUE THREAD

**Issue by jamiejackson** [obedm503/bootmark#17]
Unless I missed it, I don't see a "kitchen sink" example anywhere (https://github.com/obedm503/bootmark/issues/18). The following markdown is from my own template that I share with my team.

I'm noticing some undesirable differences between strapdown and bootmark rendering (see bottom).

# Markdown

Note, GitHub kept trying to render my triple backticks in the markdown below. Normally they wouldn't have a `\` in front of them, but I had to add them to prevent them from being interpreted.

```md
This document is written in [Markdown](http://daringfireball.net/projects/markdown) syntax. It uses Strapdown to render it on the fly: View this file in a browser to see it rendered.

See a full-fledged Markdown file [here](http://daringfireball.net/projects/markdown/syntax.text).

Note: In Firefox, this document will have an automatic, linked table of contents, by the way.

# Common Elements

## Code

### Inline

Inline code: `foobar=true;`

### Block

Here is a block of code

\```coldfusion
public string function sayHi(string who = "World") {
	return ("Hello, #arguments.who#!");
}
\```
### Table

Note: Strapdown doesn't seem to support the alignment specs.

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

## Link

Here's a [link](http://daringfireball.net/projects/markdown/syntax.text).

## Formatting

### Inline Styling
<em>HTML tags</em> can be used, but for most styling, e.g., **bold**, *emphasized*, or ***bold/emphasized*** is more readable.

### Preformatted text

	Preformatted text
	can be set off like this.

### Lists

#### Bullet

* Foo
	* Bar
		* Foobar
			> Blockquote: 
			> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	* Bar 2
		\```
		codeBlock = foo;
		\```
* Foo 2

#### Ordered

0. Foo
	0. Bar
		0. Foobar
	0. Bar 2
0. Foo 2

### Horizontal Rule

Before rule.

---

After rule.
```

# Strapdown Rendering

![strapdown](https://cloud.githubusercontent.com/assets/479475/24119027/3e89bcea-0d86-11e7-9949-23cdd1072b3b.png)

# Bootmark Rendering

![bootmark](https://cloud.githubusercontent.com/assets/479475/24119032/42e78a24-0d86-11e7-956a-1ac60c46e2b6.png)

# Differences

## The good differences in bootmark

* Table alignment seems to be supported.
* The table of contents (which was not really supported directly in strapdown) is better placed.

## The undesirable differences in bootmark (IMO):

These two are similar:

* Blockquote in a list item doesn't work. I'd like it to work as in strapdown--at the same indentation level as the list item.
* Code block in list item becomes inline. It should be on a new line and should be at the same indentation level as the list item.
* Inline HTML is stripped (see `<em>HTML tags</em> can be used` markdown). I have another ticket for that here: https://github.com/obedm503/bootmark/issues/16

FYI, GitHub renders these three items as I want them, too.

**Comment by obedm503** [comment]
as for the lists and nesting block quotes and code blocks, you should look into the [showdown options](https://github.com/showdownjs/showdown#valid-options) specifically the **disableForced4SpacesIndentedSublists** option which is why lists behave like they do.

In short the differences in rendering are due to GitHub rendering GitHub Flavored Markdown while Showdown renders vanilla markdown. 

Bootmark uses showdown for the actual markdown parsing. If you want to pass some settings to the showdown converter, use the `showdown` property in the config (similar to the `html` property)

See the docs for more: https://obedm503.github.io/bootmark/docs/#external_jQuery.fn.bootmark
