### ISSUE TITLE
Kitchen Sink Example?

### ISSUE THREAD

**Issue by jamiejackson** [obedm503/bootmark#18]
Is there a kitchen sink example for supported markdown? (I didn't spot it.)

If not, I'd recommend one.

FYI, it's not "kitchen sink" but the markdown I use in my team's strapdown template is here: https://github.com/obedm503/bootmark/issues/17

**Comment by obedm503** [comment]
there are a bunch of examples, mostly to showcase features, in the `docs/` folder. If you would like to submit a pr to the development branch with the example file in the docs folder, I'll be happy to review it. Its should be as simple as possible, so something like this?
```html
<script src="https://obedm503.github.io/bootmark/dist/bootmark.bundle.min.js"></script>
<bootmark>
## what ever markdown you need here
</bootmark>
```

**Comment by obedm503** [comment]
it's now added as `docs/markdown-cheatsheet.html`
