### ISSUE TITLE
Dynamic Content

### ISSUE THREAD

**Issue by jamiejackson** [obedm503/bootmark#2]
I have examples of documentation where I want to tailor it with a certain set of values. In other words, say I have some values (paths, for instance) that need to be different for Mac users. I'd like to have a select box at the top of the file that allows the user to switch between `Mac`, `Windows`, and `Linux`, and have that selection dynamically swap out the values that are particular to that platform. I find it hard to maintain readability when I have to show all the different values to a user who is only interested in one set.

Here was my question for Strapdown: https://github.com/arturadib/strapdown/issues/34

Is this possible in bootmark?

**Comment by obedm503** [comment]
you can specify a path and bootmark will fetch it and parse it . use the fetch option on bootmark config object

```
function parseMd(someUrl){
  bootmark.md({
    fetch:'someUrl',
    id:'someId'
  });
}
```

the md method also returns a promise which resolves with the html

> i really need to write the documentation

check the example [html https://obedm503.github.io/bootmark?fetch=README.md]
hope it helps

**Comment by obedm503** [comment]
just added some documentation and fixed some dom manipulation errors

check https://obedm503.github.io/bootmark/docs/ for more

i'll close the issue, if you need any more help feel free to open it again.
