### ISSUE TITLE
Nested Ordered/Unordered lists are not displayed properly?

### ISSUE THREAD

**Issue by jolexa** [obedm503/bootmark#21]
Hi,

(Not sure if you care about this or can fix it?)

Given the following GH Markdown:
```
1. First Item
2. Second Item
  * Sub note
3. Third Item
```

It is displayed via bootmark as:
```
1. First Item
2. Second Item
* Sub Note
1. Third Item
```

I checked multiple themes as well

**Comment by jolexa** [comment]
It looks like the Kitchen Sink example shows off this issue as well. https://obedm503.github.io/bootmark/docs/markdown-cheatsheet.html

**Comment by obedm503** [comment]
this actually is the parser's (showdown) job. to "fix" it you just have to enable the `disableForced4SpacesIndentedSublists` in the showdown config
```js
$.fn.bootmark.options = {
  showdown: {
    disableForced4SpacesIndentedSublists: true
  }
};
```
or use 4 space indents in sub items

the showdown demo
http://showdownjs.github.io/demo/#/1.%20First%20Item%0A2.%20Second%20Item%0A%20%20%20%20*%20Sub%20note%0A3.%20Third%20Item
