### ISSUE TITLE
Question: 'Responsive' images?

### ISSUE THREAD

**Issue by jolexa** [obedm503/bootmark#22]
Hello,

When embedding an image in Markdown, GitHub displays it as the width of my browser. bootmark displays it as the full size and I have to scroll right to see the full image.

So, it is possible to make this image scale within bootmark or am I missing some doc/example?

Thanks much!

**Comment by obedm503** [comment]
you could easily add the bootstrap class `img-responsive` to all images using a showdown extension. this will make all images responsive

something like this: https://jsfiddle.net/yoyrdms5/

I might add this feature later on

**Comment by jolexa** [comment]
Awesome, thanks for responding @obedm503 . I just added the extension and the page looks so much better. Here is my vote for making that default 👍
