### ISSUE TITLE
Option to disable source highlighting

### ISSUE THREAD

**Issue by urmilparikh** [obedm503/bootmark#6]
How do I disable source highlighting for code blocks?
1. It wrongly assumes `//` in `http://xyz` as comment marker
2. There is strange highlighting on 2nd line

![image](https://cloud.githubusercontent.com/assets/10322815/19375401/49ede7fc-91f1-11e6-9d94-d846092bad24.png)

**Comment by obedm503** [comment]
you can disable it or just set the language, this might be your problem

for a list of supported languages see the [code prettify faq](https://github.com/google/code-prettify/blob/master/README.md#user-content-for-which-languages-does-it-work)

but if you really want to disable to disable code highlighting (thru code prettify) you can:

if using the `<bootmark>` element add the `html` attribute and set it equal to an object with `prettify` set to `false`

``` html
<bootmark html="{ prettify: false }">
markdown here
</bootmark>
```

if using any element just add `data-`

``` html
<div class="bootmark" data-html="{ prettify: false }">
markdown here
</div>
```

or use global config options

``` js
$.fn.bootmark.options = {
  prettify: false
};
```

this is all mentioned in the [docs](https://obedm503.github.io/bootmark/docs/) and the [examples](https://obedm503.github.io/bootmark/docs/examples.html)

**Comment by urmilparikh** [comment]
The docs page looked like lot of code, so I overlooked it.
Anyway, `prettify: false` worked, thanks a lot!
