### ISSUE TITLE
Issue with printing: links

### ISSUE THREAD

**Issue by urmilparikh** [obedm503/bootmark#7]
When printing, it shows links along with labels:
![image](https://cloud.githubusercontent.com/assets/10322815/19375460/fd79f112-91f1-11e6-9129-7d587e8156e8.png)

**Comment by obedm503** [comment]
what browser are you using? in chrome it's working fine

![1](https://cloud.githubusercontent.com/assets/9118707/19375722/590233c2-9194-11e6-87f4-9c63535c9de3.png)

can you provide more information about this issue

**Comment by urmilparikh** [comment]
It works well in browser. The issue occurs when you try to print the page (Ctrl+P).

**Comment by obedm503** [comment]
turns out it's something with bootstrap. It'll be fixed on the next relase. Thanks for reporting it.

This is now available on the development branch.

**Comment by obedm503** [comment]
This is now on the latest stable release v[0.6.1](https://github.com/obedm503/bootmark/tree/0.6.1)
