### ISSUE TITLE
Conditional text screen vs print

### ISSUE THREAD

**Issue by urmilparikh** [obedm503/bootmark#8]
This may not be directly related to bootmark, but I would like to know if there is any way I can have conditional text so that there is different text displayed when seen on screen (web) vs when someone takes a printout.

For example, I want to have a labelled link for screen (can be clicked) but a shortened URL for print (for reader to type manually).

**Comment by obedm503** [comment]
shortened url's can still be clicked. by default bootmark uses showdown with `simplifiedAutoLink: true`, so links without the `[ text ]( //url )` notation will be parsed as links.

But the idea of having different text for print than for web is still interesting

**Comment by urmilparikh** [comment]
Adding support for attribute list can solve this, as well as make it more flexible.
Please consider this feature.

https://pythonhosted.org/Markdown/extensions/attr_list.html

**Comment by obedm503** [comment]
this has already been brought to the attention of the showdown parser.

showdownjs/showdown#195

**Comment by obedm503** [comment]
closing because this concerns showdown and not bootmark
